name: Documentation

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and publish documentation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          brew install boost
          brew install doxygen
          pip3 install jinja2 Pygments

      - name: Build
        run: |
          cmake -Hdocumentation -Bbuild
          cmake --build build --target GenerateDocs

      - name: Preparing tag
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doxygen/html
          tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          tag_message: 'Deployment ${{ steps.prepare_tag.outputs.tag_name }}'
