name: Standalone

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    #- name: Install dependencies
      #run: |
        #sudo add-apt-repository ppa:mhier/libboost-latest
        #sudo apt-get update
        #sudo apt-get install libboost1.74 libboost1.74-dev -y

    - name: Export boost environment
      run: "export BOOST_ROOT=$BOOST_ROOT_1_72_0"

    - name: configure
      run: BOOST_ROOT=$BOOST_ROOT_1_72_0 cmake -Hstandalone -Bbuild

    - name: build
      run: cmake --build build -j4

    - name: run
      run: |
        echo -ne "\n" | ./build/server
